### ISSUE TITLE
Segunda corerção

### ISSUE THREAD

**Issue by ubirajarapelli** [GusNachbar/Tarefa-Supervisionada#2]
```css
 #janela1{ width: 900px;}      
 #janela2{
    background-color: rgb(245,245,245);
    width: 900px;
}
 #janela3{ width: 900px; }
 #janela4{ width: 900px; }
```

Concorda que todos esses IDs estão fazendo praticamente a mesma coisa (Voce deu o nome de janela e todos eles tem 900px), nesse caso, não repetir o código (900px para a "janela" )é uma boa prática, troca para uma Classs  ex. 
```css 
.janela { width: 900px }
```
e a que tem o background, inicialmente voce pode add o ID somente com a cor de fundo.

O mesmo conceito para os `.pontosdeInteresse1` e para `.profissionais` uma classe ja resolve o problema.
e a nomenclatura `.ponto-de-interesse`. 

Tem um lance dentro da programação  chamado DRY (Don't Repeat Youself) lembra sempre disso.

`<h1>Crie agora seu app para sua <br> empresa</h1>` : Não usar um `br` dentro de h1-h6

`<img src=".." width="90"; height="90";..> ` Boa pratica,  Não usar tamanhos dentro de elementos html, use:

```css
.profissionais img {
    width: 90px; 
    height: 90px;
}
```

```html
<input type="text"; id="Nome"; name="Nome"; required>
```
Os `; ` nesse trecho vai dar ruim, eles não deveriam estar ai, e as letras maiusculas tbm não devem ser usadas. 

```html
<select name="o_que_deseja", id="o_que_deseja">
```
usar `name="o-que-deseja"`
